name: Delete Old Main Tags

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-main'

jobs:
  delete_old_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get all tags
        id: get_tags
        run: |
          git fetch --tags
          git tag --list 'v[0-9]*.[0-9]*.[0-9]*-main' > all_tags.txt

      - name: Delete old tags
        run: |
          NEW_TAG=${GITHUB_REF#refs/tags/}
          while IFS= read -r TAG; do
            if [ "$TAG" != "$NEW_TAG" ]; then
              git tag -d "$TAG"
              git push origin :refs/tags/"$TAG"
            fi
          done < all_tags.txt