name: Call Update Version Workflow from a reusable workflow

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version to set in package.json'
        required: true
        type: string

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
    - name: Call Update Version Workflow
      uses: taiga-organization-sandbox/taiga-org-gh-actions-packages/.github/workflows/github-app-push@v1.0.2
      with:
        new_version: ${{ github.event.inputs.new_version }}